onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp4_tb/f
add wave -noupdate /mp4_tb/f
add wave -noupdate /mp4_tb/dut/datapath/clk
add wave -noupdate /mp4_tb/dut/datapath/rst
add wave -noupdate /mp4_tb/dut/datapath/pmem_iresp
add wave -noupdate /mp4_tb/dut/datapath/pmem_irdata
add wave -noupdate /mp4_tb/dut/datapath/pmem_iaddress
add wave -noupdate /mp4_tb/dut/datapath/pmem_iwdata
add wave -noupdate /mp4_tb/dut/datapath/pmem_iread
add wave -noupdate /mp4_tb/dut/datapath/pmem_iwrite
add wave -noupdate /mp4_tb/dut/datapath/pmem_dresp
add wave -noupdate /mp4_tb/dut/datapath/pmem_drdata
add wave -noupdate /mp4_tb/dut/datapath/pmem_dmbe
add wave -noupdate /mp4_tb/dut/datapath/pmem_daddress
add wave -noupdate /mp4_tb/dut/datapath/pmem_dwdata
add wave -noupdate /mp4_tb/dut/datapath/pmem_dread
add wave -noupdate /mp4_tb/dut/datapath/pmem_dwrite
add wave -noupdate /mp4_tb/dut/datapath/d_miss
add wave -noupdate /mp4_tb/dut/datapath/IF_resp
add wave -noupdate /mp4_tb/dut/datapath/MEM_resp
add wave -noupdate /mp4_tb/dut/datapath/stage_register_reset
add wave -noupdate /mp4_tb/dut/datapath/PCSrc
add wave -noupdate /mp4_tb/dut/datapath/PCWrite
add wave -noupdate /mp4_tb/dut/datapath/IF_PC
add wave -noupdate /mp4_tb/dut/datapath/IF_Instruction
add wave -noupdate /mp4_tb/dut/datapath/if_id_load
add wave -noupdate /mp4_tb/dut/datapath/if_id_write
add wave -noupdate /mp4_tb/dut/datapath/RegWrite
add wave -noupdate /mp4_tb/dut/datapath/ID_Instruction
add wave -noupdate /mp4_tb/dut/datapath/ID_RS1
add wave -noupdate /mp4_tb/dut/datapath/ID_RS2
add wave -noupdate /mp4_tb/dut/datapath/ID_RD
add wave -noupdate /mp4_tb/dut/datapath/ID_PC
add wave -noupdate /mp4_tb/dut/datapath/ID_Read_Data1
add wave -noupdate /mp4_tb/dut/datapath/ID_Read_Data2
add wave -noupdate /mp4_tb/dut/datapath/ID_imm
add wave -noupdate /mp4_tb/dut/datapath/ID_funct
add wave -noupdate /mp4_tb/dut/datapath/ID_control
add wave -noupdate /mp4_tb/dut/datapath/id_ex_load
add wave -noupdate /mp4_tb/dut/datapath/EX_PC
add wave -noupdate /mp4_tb/dut/datapath/EX_Read_Data1
add wave -noupdate /mp4_tb/dut/datapath/EX_Read_Data2
add wave -noupdate /mp4_tb/dut/datapath/EX_imm
add wave -noupdate /mp4_tb/dut/datapath/EX_ADD
add wave -noupdate /mp4_tb/dut/datapath/EX_ZERO
add wave -noupdate /mp4_tb/dut/datapath/EX_RESULT
add wave -noupdate /mp4_tb/dut/datapath/EX_ALU_IN1
add wave -noupdate /mp4_tb/dut/datapath/EX_ALU_IN2
add wave -noupdate /mp4_tb/dut/datapath/EX_RS1
add wave -noupdate /mp4_tb/dut/datapath/EX_RS2
add wave -noupdate /mp4_tb/dut/datapath/EX_RD
add wave -noupdate /mp4_tb/dut/datapath/EX_funct
add wave -noupdate /mp4_tb/dut/datapath/EX_control
add wave -noupdate /mp4_tb/dut/datapath/ex_mem_load
add wave -noupdate /mp4_tb/dut/datapath/MEM_control
add wave -noupdate /mp4_tb/dut/datapath/MEM_ZERO
add wave -noupdate /mp4_tb/dut/datapath/MEM_RESULT
add wave -noupdate /mp4_tb/dut/datapath/MEM_ADD
add wave -noupdate /mp4_tb/dut/datapath/MEM_ALU_IN1
add wave -noupdate /mp4_tb/dut/datapath/MEM_ALU_IN2
add wave -noupdate /mp4_tb/dut/datapath/MEM_RD
add wave -noupdate /mp4_tb/dut/datapath/MEM_Read_Data
add wave -noupdate /mp4_tb/dut/datapath/mem_wb_load
add wave -noupdate /mp4_tb/dut/datapath/MEM_funct
add wave -noupdate /mp4_tb/dut/datapath/MEM_lui
add wave -noupdate /mp4_tb/dut/datapath/WB_RESULT
add wave -noupdate /mp4_tb/dut/datapath/WB_RD
add wave -noupdate /mp4_tb/dut/datapath/WB_mux_out
add wave -noupdate /mp4_tb/dut/datapath/WB_Read_Data
add wave -noupdate /mp4_tb/dut/datapath/WB_lui
add wave -noupdate /mp4_tb/dut/datapath/WB_auipc
add wave -noupdate /mp4_tb/dut/datapath/WB_control
add wave -noupdate /mp4_tb/dut/datapath/id_stage/regfile/data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4587043 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 337
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {4270386 ps} {5535536 ps}
